/**
 * Access to the published photo set and its attribution.
 *
 * `public/photos/credits.json` is generated by scripts/photos/webify.py from the
 * Commons manifest plus the human curation pass. It is the authority on which
 * images exist, what widths were rendered, where each should be cropped, and
 * what its licence obliges us to say.
 *
 * Reading credits from the same file that generated the derivatives is what
 * stops a credit drifting away from its image.
 */
import credits from "../../public/photos/credits.json";

export interface PhotoCredit {
  title: string;
  author: string;
  licence: string;
  source: string;
  attributionRequired: boolean;
  shareAlike: boolean;
  /** object-position from curation. A default centre crop loses low subjects. */
  focus: string;
  role: "hero" | "gallery" | "texture";
  widths: number[];
}

export const CREDITS = credits as unknown as Record<string, PhotoCredit>;

export const photo = (id: string): PhotoCredit => {
  const c = CREDITS[id];
  if (!c) throw new Error(`Unknown photo id "${id}" - not in public/photos/credits.json`);
  return c;
};

export const srcset = (id: string): string =>
  photo(id).widths.map((w) => `/photos/${id}-${w}.webp ${w}w`).join(", ");

export const src = (id: string): string => {
  const c = photo(id);
  return `/photos/${id}-${c.widths[c.widths.length - 1]}.webp`;
};
