/**
 * Access to the published photo set and its attribution.
 *
 * `public/photos/credits.json` is generated by scripts/photos/webify.py from
 * the Commons manifest plus the visual curation pass. It is the authority on
 * which images exist, what sizes were rendered, where each one should be
 * cropped, and — importantly — what each one's licence obliges us to say.
 *
 * 42 of the 49 published photographs require attribution as a *condition of the
 * licence*. Reading it from the same file that generated the derivatives means
 * a credit cannot drift away from its image.
 */
import credits from "../../public/photos/credits.json";

export interface PhotoCredit {
  title: string;
  author: string;
  licence: string;
  source: string;
  attributionRequired: boolean;
  shareAlike: boolean;
  focus: string;
  role: "hero" | "gallery" | "texture";
  widths: number[];
}

export const CREDITS = credits as unknown as Record<string, PhotoCredit>;

export const photo = (id: string): PhotoCredit => {
  const c = CREDITS[id];
  if (!c) throw new Error(`Unknown photo id "${id}" — not in public/photos/credits.json`);
  return c;
};

export const hasPhoto = (id: string): boolean => id in CREDITS;

/** srcset across every width actually rendered for this image. */
export const srcset = (id: string): string =>
  photo(id).widths.map((w) => `/photos/${id}-${w}.webp ${w}w`).join(", ");

/** Largest rendered width, for the `src` fallback. */
export const src = (id: string): string => {
  const c = photo(id);
  return `/photos/${id}-${c.widths[c.widths.length - 1]}.webp`;
};

/** Every credit that must be shown, sorted for the credits page. */
export const attributions = (): Array<[string, PhotoCredit]> =>
  Object.entries(CREDITS)
    .filter(([, c]) => c.attributionRequired)
    .sort(([a], [b]) => a.localeCompare(b));

/** Compact inline credit line, e.g. "Jane Doe / CC BY-SA 4.0". */
export const creditLine = (id: string): string => {
  const c = photo(id);
  const author = c.author.replace(/\s+/g, " ").trim() || "Unknown";
  return `${author} / ${c.licence}`;
};
